name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]

# Ép hệ thống sử dụng Node.js 24 để loại bỏ cảnh báo deprecation
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

permissions:
  contents: read
  pages: write
  id-token: write

# Đảm bảo chỉ có một luồng triển khai chạy tại một thời điểm
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Đường dẫn tới thư mục chứa tệp tĩnh của bạn (ví dụ: index.html)
          path: './public'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
